// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package http_after_response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// CreateHTTPAfterResponseRuleReader is a Reader for the CreateHTTPAfterResponseRule structure.
type CreateHTTPAfterResponseRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateHTTPAfterResponseRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateHTTPAfterResponseRuleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewCreateHTTPAfterResponseRuleAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateHTTPAfterResponseRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateHTTPAfterResponseRuleConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateHTTPAfterResponseRuleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateHTTPAfterResponseRuleCreated creates a CreateHTTPAfterResponseRuleCreated with default headers values
func NewCreateHTTPAfterResponseRuleCreated() *CreateHTTPAfterResponseRuleCreated {
	return &CreateHTTPAfterResponseRuleCreated{}
}

/* CreateHTTPAfterResponseRuleCreated describes a response with status code 201, with default header values.

HTTP Response Rule created
*/
type CreateHTTPAfterResponseRuleCreated struct {
	Payload *models.HTTPAfterResponseRule
}

func (o *CreateHTTPAfterResponseRuleCreated) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_after_response_rules][%d] createHttpAfterResponseRuleCreated  %+v", 201, o.Payload)
}
func (o *CreateHTTPAfterResponseRuleCreated) GetPayload() *models.HTTPAfterResponseRule {
	return o.Payload
}

func (o *CreateHTTPAfterResponseRuleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAfterResponseRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPAfterResponseRuleAccepted creates a CreateHTTPAfterResponseRuleAccepted with default headers values
func NewCreateHTTPAfterResponseRuleAccepted() *CreateHTTPAfterResponseRuleAccepted {
	return &CreateHTTPAfterResponseRuleAccepted{}
}

/* CreateHTTPAfterResponseRuleAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type CreateHTTPAfterResponseRuleAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string

	Payload *models.HTTPAfterResponseRule
}

func (o *CreateHTTPAfterResponseRuleAccepted) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_after_response_rules][%d] createHttpAfterResponseRuleAccepted  %+v", 202, o.Payload)
}
func (o *CreateHTTPAfterResponseRuleAccepted) GetPayload() *models.HTTPAfterResponseRule {
	return o.Payload
}

func (o *CreateHTTPAfterResponseRuleAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	o.Payload = new(models.HTTPAfterResponseRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPAfterResponseRuleBadRequest creates a CreateHTTPAfterResponseRuleBadRequest with default headers values
func NewCreateHTTPAfterResponseRuleBadRequest() *CreateHTTPAfterResponseRuleBadRequest {
	return &CreateHTTPAfterResponseRuleBadRequest{}
}

/* CreateHTTPAfterResponseRuleBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateHTTPAfterResponseRuleBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *CreateHTTPAfterResponseRuleBadRequest) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_after_response_rules][%d] createHttpAfterResponseRuleBadRequest  %+v", 400, o.Payload)
}
func (o *CreateHTTPAfterResponseRuleBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPAfterResponseRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPAfterResponseRuleConflict creates a CreateHTTPAfterResponseRuleConflict with default headers values
func NewCreateHTTPAfterResponseRuleConflict() *CreateHTTPAfterResponseRuleConflict {
	return &CreateHTTPAfterResponseRuleConflict{}
}

/* CreateHTTPAfterResponseRuleConflict describes a response with status code 409, with default header values.

The specified resource already exists
*/
type CreateHTTPAfterResponseRuleConflict struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *CreateHTTPAfterResponseRuleConflict) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_after_response_rules][%d] createHttpAfterResponseRuleConflict  %+v", 409, o.Payload)
}
func (o *CreateHTTPAfterResponseRuleConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPAfterResponseRuleConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateHTTPAfterResponseRuleDefault creates a CreateHTTPAfterResponseRuleDefault with default headers values
func NewCreateHTTPAfterResponseRuleDefault(code int) *CreateHTTPAfterResponseRuleDefault {
	return &CreateHTTPAfterResponseRuleDefault{
		_statusCode: code,
	}
}

/* CreateHTTPAfterResponseRuleDefault describes a response with status code -1, with default header values.

General Error
*/
type CreateHTTPAfterResponseRuleDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the create HTTP after response rule default response
func (o *CreateHTTPAfterResponseRuleDefault) Code() int {
	return o._statusCode
}

func (o *CreateHTTPAfterResponseRuleDefault) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/configuration/http_after_response_rules][%d] createHTTPAfterResponseRule default  %+v", o._statusCode, o.Payload)
}
func (o *CreateHTTPAfterResponseRuleDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateHTTPAfterResponseRuleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
