// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package userlist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserlistParams creates a new GetUserlistParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserlistParams() *GetUserlistParams {
	return &GetUserlistParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserlistParamsWithTimeout creates a new GetUserlistParams object
// with the ability to set a timeout on a request.
func NewGetUserlistParamsWithTimeout(timeout time.Duration) *GetUserlistParams {
	return &GetUserlistParams{
		timeout: timeout,
	}
}

// NewGetUserlistParamsWithContext creates a new GetUserlistParams object
// with the ability to set a context for a request.
func NewGetUserlistParamsWithContext(ctx context.Context) *GetUserlistParams {
	return &GetUserlistParams{
		Context: ctx,
	}
}

// NewGetUserlistParamsWithHTTPClient creates a new GetUserlistParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserlistParamsWithHTTPClient(client *http.Client) *GetUserlistParams {
	return &GetUserlistParams{
		HTTPClient: client,
	}
}

/* GetUserlistParams contains all the parameters to send to the API endpoint
   for the get userlist operation.

   Typically these are written to a http.Request.
*/
type GetUserlistParams struct {

	/* Name.

	   Userlist name
	*/
	Name string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get userlist params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserlistParams) WithDefaults() *GetUserlistParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get userlist params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserlistParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get userlist params
func (o *GetUserlistParams) WithTimeout(timeout time.Duration) *GetUserlistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get userlist params
func (o *GetUserlistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get userlist params
func (o *GetUserlistParams) WithContext(ctx context.Context) *GetUserlistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get userlist params
func (o *GetUserlistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get userlist params
func (o *GetUserlistParams) WithHTTPClient(client *http.Client) *GetUserlistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get userlist params
func (o *GetUserlistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get userlist params
func (o *GetUserlistParams) WithName(name string) *GetUserlistParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get userlist params
func (o *GetUserlistParams) SetName(name string) {
	o.Name = name
}

// WithTransactionID adds the transactionID to the get userlist params
func (o *GetUserlistParams) WithTransactionID(transactionID *string) *GetUserlistParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get userlist params
func (o *GetUserlistParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserlistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
