// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package dgram_bind

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// DeleteDgramBindReader is a Reader for the DeleteDgramBind structure.
type DeleteDgramBindReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDgramBindReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteDgramBindAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteDgramBindNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteDgramBindNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteDgramBindDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDgramBindAccepted creates a DeleteDgramBindAccepted with default headers values
func NewDeleteDgramBindAccepted() *DeleteDgramBindAccepted {
	return &DeleteDgramBindAccepted{}
}

/* DeleteDgramBindAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type DeleteDgramBindAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string
}

func (o *DeleteDgramBindAccepted) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/dgram_binds/{name}][%d] deleteDgramBindAccepted ", 202)
}

func (o *DeleteDgramBindAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	return nil
}

// NewDeleteDgramBindNoContent creates a DeleteDgramBindNoContent with default headers values
func NewDeleteDgramBindNoContent() *DeleteDgramBindNoContent {
	return &DeleteDgramBindNoContent{}
}

/* DeleteDgramBindNoContent describes a response with status code 204, with default header values.

Bind deleted
*/
type DeleteDgramBindNoContent struct {
}

func (o *DeleteDgramBindNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/dgram_binds/{name}][%d] deleteDgramBindNoContent ", 204)
}

func (o *DeleteDgramBindNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDgramBindNotFound creates a DeleteDgramBindNotFound with default headers values
func NewDeleteDgramBindNotFound() *DeleteDgramBindNotFound {
	return &DeleteDgramBindNotFound{}
}

/* DeleteDgramBindNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type DeleteDgramBindNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *DeleteDgramBindNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/dgram_binds/{name}][%d] deleteDgramBindNotFound  %+v", 404, o.Payload)
}
func (o *DeleteDgramBindNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDgramBindNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDgramBindDefault creates a DeleteDgramBindDefault with default headers values
func NewDeleteDgramBindDefault(code int) *DeleteDgramBindDefault {
	return &DeleteDgramBindDefault{
		_statusCode: code,
	}
}

/* DeleteDgramBindDefault describes a response with status code -1, with default header values.

General Error
*/
type DeleteDgramBindDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the delete dgram bind default response
func (o *DeleteDgramBindDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDgramBindDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/dgram_binds/{name}][%d] deleteDgramBind default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteDgramBindDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDgramBindDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
