// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package http_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// DeleteHTTPCheckReader is a Reader for the DeleteHTTPCheck structure.
type DeleteHTTPCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHTTPCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteHTTPCheckAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteHTTPCheckNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteHTTPCheckNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteHTTPCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteHTTPCheckAccepted creates a DeleteHTTPCheckAccepted with default headers values
func NewDeleteHTTPCheckAccepted() *DeleteHTTPCheckAccepted {
	return &DeleteHTTPCheckAccepted{}
}

/* DeleteHTTPCheckAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type DeleteHTTPCheckAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string
}

func (o *DeleteHTTPCheckAccepted) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/http_checks/{index}][%d] deleteHttpCheckAccepted ", 202)
}

func (o *DeleteHTTPCheckAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	return nil
}

// NewDeleteHTTPCheckNoContent creates a DeleteHTTPCheckNoContent with default headers values
func NewDeleteHTTPCheckNoContent() *DeleteHTTPCheckNoContent {
	return &DeleteHTTPCheckNoContent{}
}

/* DeleteHTTPCheckNoContent describes a response with status code 204, with default header values.

HTTP check deleted
*/
type DeleteHTTPCheckNoContent struct {
}

func (o *DeleteHTTPCheckNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/http_checks/{index}][%d] deleteHttpCheckNoContent ", 204)
}

func (o *DeleteHTTPCheckNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHTTPCheckNotFound creates a DeleteHTTPCheckNotFound with default headers values
func NewDeleteHTTPCheckNotFound() *DeleteHTTPCheckNotFound {
	return &DeleteHTTPCheckNotFound{}
}

/* DeleteHTTPCheckNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type DeleteHTTPCheckNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *DeleteHTTPCheckNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/http_checks/{index}][%d] deleteHttpCheckNotFound  %+v", 404, o.Payload)
}
func (o *DeleteHTTPCheckNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteHTTPCheckNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteHTTPCheckDefault creates a DeleteHTTPCheckDefault with default headers values
func NewDeleteHTTPCheckDefault(code int) *DeleteHTTPCheckDefault {
	return &DeleteHTTPCheckDefault{
		_statusCode: code,
	}
}

/* DeleteHTTPCheckDefault describes a response with status code -1, with default header values.

General Error
*/
type DeleteHTTPCheckDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the delete HTTP check default response
func (o *DeleteHTTPCheckDefault) Code() int {
	return o._statusCode
}

func (o *DeleteHTTPCheckDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/configuration/http_checks/{index}][%d] deleteHTTPCheck default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteHTTPCheckDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteHTTPCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
