// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package http_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHTTPChecksParams creates a new GetHTTPChecksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHTTPChecksParams() *GetHTTPChecksParams {
	return &GetHTTPChecksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHTTPChecksParamsWithTimeout creates a new GetHTTPChecksParams object
// with the ability to set a timeout on a request.
func NewGetHTTPChecksParamsWithTimeout(timeout time.Duration) *GetHTTPChecksParams {
	return &GetHTTPChecksParams{
		timeout: timeout,
	}
}

// NewGetHTTPChecksParamsWithContext creates a new GetHTTPChecksParams object
// with the ability to set a context for a request.
func NewGetHTTPChecksParamsWithContext(ctx context.Context) *GetHTTPChecksParams {
	return &GetHTTPChecksParams{
		Context: ctx,
	}
}

// NewGetHTTPChecksParamsWithHTTPClient creates a new GetHTTPChecksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHTTPChecksParamsWithHTTPClient(client *http.Client) *GetHTTPChecksParams {
	return &GetHTTPChecksParams{
		HTTPClient: client,
	}
}

/* GetHTTPChecksParams contains all the parameters to send to the API endpoint
   for the get HTTP checks operation.

   Typically these are written to a http.Request.
*/
type GetHTTPChecksParams struct {

	/* ParentName.

	   Parent name
	*/
	ParentName *string

	/* ParentType.

	   Parent type
	*/
	ParentType string

	/* TransactionID.

	   ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get HTTP checks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPChecksParams) WithDefaults() *GetHTTPChecksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get HTTP checks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPChecksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get HTTP checks params
func (o *GetHTTPChecksParams) WithTimeout(timeout time.Duration) *GetHTTPChecksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get HTTP checks params
func (o *GetHTTPChecksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get HTTP checks params
func (o *GetHTTPChecksParams) WithContext(ctx context.Context) *GetHTTPChecksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get HTTP checks params
func (o *GetHTTPChecksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get HTTP checks params
func (o *GetHTTPChecksParams) WithHTTPClient(client *http.Client) *GetHTTPChecksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get HTTP checks params
func (o *GetHTTPChecksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParentName adds the parentName to the get HTTP checks params
func (o *GetHTTPChecksParams) WithParentName(parentName *string) *GetHTTPChecksParams {
	o.SetParentName(parentName)
	return o
}

// SetParentName adds the parentName to the get HTTP checks params
func (o *GetHTTPChecksParams) SetParentName(parentName *string) {
	o.ParentName = parentName
}

// WithParentType adds the parentType to the get HTTP checks params
func (o *GetHTTPChecksParams) WithParentType(parentType string) *GetHTTPChecksParams {
	o.SetParentType(parentType)
	return o
}

// SetParentType adds the parentType to the get HTTP checks params
func (o *GetHTTPChecksParams) SetParentType(parentType string) {
	o.ParentType = parentType
}

// WithTransactionID adds the transactionID to the get HTTP checks params
func (o *GetHTTPChecksParams) WithTransactionID(transactionID *string) *GetHTTPChecksParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get HTTP checks params
func (o *GetHTTPChecksParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHTTPChecksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ParentName != nil {

		// query param parent_name
		var qrParentName string

		if o.ParentName != nil {
			qrParentName = *o.ParentName
		}
		qParentName := qrParentName
		if qParentName != "" {

			if err := r.SetQueryParam("parent_name", qParentName); err != nil {
				return err
			}
		}
	}

	// query param parent_type
	qrParentType := o.ParentType
	qParentType := qrParentType
	if qParentType != "" {

		if err := r.SetQueryParam("parent_type", qParentType); err != nil {
			return err
		}
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string

		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {

			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
