// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOneStorageGeneralFileParams creates a new GetOneStorageGeneralFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOneStorageGeneralFileParams() *GetOneStorageGeneralFileParams {
	return &GetOneStorageGeneralFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOneStorageGeneralFileParamsWithTimeout creates a new GetOneStorageGeneralFileParams object
// with the ability to set a timeout on a request.
func NewGetOneStorageGeneralFileParamsWithTimeout(timeout time.Duration) *GetOneStorageGeneralFileParams {
	return &GetOneStorageGeneralFileParams{
		timeout: timeout,
	}
}

// NewGetOneStorageGeneralFileParamsWithContext creates a new GetOneStorageGeneralFileParams object
// with the ability to set a context for a request.
func NewGetOneStorageGeneralFileParamsWithContext(ctx context.Context) *GetOneStorageGeneralFileParams {
	return &GetOneStorageGeneralFileParams{
		Context: ctx,
	}
}

// NewGetOneStorageGeneralFileParamsWithHTTPClient creates a new GetOneStorageGeneralFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOneStorageGeneralFileParamsWithHTTPClient(client *http.Client) *GetOneStorageGeneralFileParams {
	return &GetOneStorageGeneralFileParams{
		HTTPClient: client,
	}
}

/* GetOneStorageGeneralFileParams contains all the parameters to send to the API endpoint
   for the get one storage general file operation.

   Typically these are written to a http.Request.
*/
type GetOneStorageGeneralFileParams struct {

	/* Name.

	   General use file storage_name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get one storage general file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOneStorageGeneralFileParams) WithDefaults() *GetOneStorageGeneralFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get one storage general file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOneStorageGeneralFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) WithTimeout(timeout time.Duration) *GetOneStorageGeneralFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) WithContext(ctx context.Context) *GetOneStorageGeneralFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) WithHTTPClient(client *http.Client) *GetOneStorageGeneralFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) WithName(name string) *GetOneStorageGeneralFileParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get one storage general file params
func (o *GetOneStorageGeneralFileParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetOneStorageGeneralFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
