// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haproxytech/client-native/v4/models"
)

// ReplaceStorageGeneralFileReader is a Reader for the ReplaceStorageGeneralFile structure.
type ReplaceStorageGeneralFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceStorageGeneralFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewReplaceStorageGeneralFileAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewReplaceStorageGeneralFileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReplaceStorageGeneralFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReplaceStorageGeneralFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewReplaceStorageGeneralFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceStorageGeneralFileAccepted creates a ReplaceStorageGeneralFileAccepted with default headers values
func NewReplaceStorageGeneralFileAccepted() *ReplaceStorageGeneralFileAccepted {
	return &ReplaceStorageGeneralFileAccepted{}
}

/* ReplaceStorageGeneralFileAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type ReplaceStorageGeneralFileAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string
}

func (o *ReplaceStorageGeneralFileAccepted) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/storage/general/{name}][%d] replaceStorageGeneralFileAccepted ", 202)
}

func (o *ReplaceStorageGeneralFileAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	return nil
}

// NewReplaceStorageGeneralFileNoContent creates a ReplaceStorageGeneralFileNoContent with default headers values
func NewReplaceStorageGeneralFileNoContent() *ReplaceStorageGeneralFileNoContent {
	return &ReplaceStorageGeneralFileNoContent{}
}

/* ReplaceStorageGeneralFileNoContent describes a response with status code 204, with default header values.

General use file replaced
*/
type ReplaceStorageGeneralFileNoContent struct {
}

func (o *ReplaceStorageGeneralFileNoContent) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/storage/general/{name}][%d] replaceStorageGeneralFileNoContent ", 204)
}

func (o *ReplaceStorageGeneralFileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReplaceStorageGeneralFileBadRequest creates a ReplaceStorageGeneralFileBadRequest with default headers values
func NewReplaceStorageGeneralFileBadRequest() *ReplaceStorageGeneralFileBadRequest {
	return &ReplaceStorageGeneralFileBadRequest{}
}

/* ReplaceStorageGeneralFileBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ReplaceStorageGeneralFileBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *ReplaceStorageGeneralFileBadRequest) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/storage/general/{name}][%d] replaceStorageGeneralFileBadRequest  %+v", 400, o.Payload)
}
func (o *ReplaceStorageGeneralFileBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceStorageGeneralFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceStorageGeneralFileNotFound creates a ReplaceStorageGeneralFileNotFound with default headers values
func NewReplaceStorageGeneralFileNotFound() *ReplaceStorageGeneralFileNotFound {
	return &ReplaceStorageGeneralFileNotFound{}
}

/* ReplaceStorageGeneralFileNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type ReplaceStorageGeneralFileNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *ReplaceStorageGeneralFileNotFound) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/storage/general/{name}][%d] replaceStorageGeneralFileNotFound  %+v", 404, o.Payload)
}
func (o *ReplaceStorageGeneralFileNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceStorageGeneralFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceStorageGeneralFileDefault creates a ReplaceStorageGeneralFileDefault with default headers values
func NewReplaceStorageGeneralFileDefault(code int) *ReplaceStorageGeneralFileDefault {
	return &ReplaceStorageGeneralFileDefault{
		_statusCode: code,
	}
}

/* ReplaceStorageGeneralFileDefault describes a response with status code -1, with default header values.

General Error
*/
type ReplaceStorageGeneralFileDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the replace storage general file default response
func (o *ReplaceStorageGeneralFileDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceStorageGeneralFileDefault) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/storage/general/{name}][%d] replaceStorageGeneralFile default  %+v", o._statusCode, o.Payload)
}
func (o *ReplaceStorageGeneralFileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceStorageGeneralFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
