// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package log_forward

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// ReplaceLogForwardReader is a Reader for the ReplaceLogForward structure.
type ReplaceLogForwardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceLogForwardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceLogForwardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewReplaceLogForwardAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReplaceLogForwardBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReplaceLogForwardNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewReplaceLogForwardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceLogForwardOK creates a ReplaceLogForwardOK with default headers values
func NewReplaceLogForwardOK() *ReplaceLogForwardOK {
	return &ReplaceLogForwardOK{}
}

/* ReplaceLogForwardOK describes a response with status code 200, with default header values.

Log Forward replaced
*/
type ReplaceLogForwardOK struct {
	Payload *models.LogForward
}

func (o *ReplaceLogForwardOK) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/log_forwards/{name}][%d] replaceLogForwardOK  %+v", 200, o.Payload)
}
func (o *ReplaceLogForwardOK) GetPayload() *models.LogForward {
	return o.Payload
}

func (o *ReplaceLogForwardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LogForward)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceLogForwardAccepted creates a ReplaceLogForwardAccepted with default headers values
func NewReplaceLogForwardAccepted() *ReplaceLogForwardAccepted {
	return &ReplaceLogForwardAccepted{}
}

/* ReplaceLogForwardAccepted describes a response with status code 202, with default header values.

Configuration change accepted and reload requested
*/
type ReplaceLogForwardAccepted struct {

	/* ID of the requested reload
	 */
	ReloadID string

	Payload *models.LogForward
}

func (o *ReplaceLogForwardAccepted) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/log_forwards/{name}][%d] replaceLogForwardAccepted  %+v", 202, o.Payload)
}
func (o *ReplaceLogForwardAccepted) GetPayload() *models.LogForward {
	return o.Payload
}

func (o *ReplaceLogForwardAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Reload-ID
	hdrReloadID := response.GetHeader("Reload-ID")

	if hdrReloadID != "" {
		o.ReloadID = hdrReloadID
	}

	o.Payload = new(models.LogForward)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceLogForwardBadRequest creates a ReplaceLogForwardBadRequest with default headers values
func NewReplaceLogForwardBadRequest() *ReplaceLogForwardBadRequest {
	return &ReplaceLogForwardBadRequest{}
}

/* ReplaceLogForwardBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ReplaceLogForwardBadRequest struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *ReplaceLogForwardBadRequest) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/log_forwards/{name}][%d] replaceLogForwardBadRequest  %+v", 400, o.Payload)
}
func (o *ReplaceLogForwardBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceLogForwardBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceLogForwardNotFound creates a ReplaceLogForwardNotFound with default headers values
func NewReplaceLogForwardNotFound() *ReplaceLogForwardNotFound {
	return &ReplaceLogForwardNotFound{}
}

/* ReplaceLogForwardNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type ReplaceLogForwardNotFound struct {

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *ReplaceLogForwardNotFound) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/log_forwards/{name}][%d] replaceLogForwardNotFound  %+v", 404, o.Payload)
}
func (o *ReplaceLogForwardNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceLogForwardNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceLogForwardDefault creates a ReplaceLogForwardDefault with default headers values
func NewReplaceLogForwardDefault(code int) *ReplaceLogForwardDefault {
	return &ReplaceLogForwardDefault{
		_statusCode: code,
	}
}

/* ReplaceLogForwardDefault describes a response with status code -1, with default header values.

General Error
*/
type ReplaceLogForwardDefault struct {
	_statusCode int

	/* Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the replace log forward default response
func (o *ReplaceLogForwardDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceLogForwardDefault) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/configuration/log_forwards/{name}][%d] replaceLogForward default  %+v", o._statusCode, o.Payload)
}
func (o *ReplaceLogForwardDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceLogForwardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Configuration-Version
	hdrConfigurationVersion := response.GetHeader("Configuration-Version")

	if hdrConfigurationVersion != "" {
		o.ConfigurationVersion = hdrConfigurationVersion
	}

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
