// Code generated by go-swagger; DO NOT EDIT.

// /*
// MIT License
//
// Copyright (c) 2022 Carlos Eduardo de Paula
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// */
//
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Resolver Resolver
//
// Runtime DNS configuration
//
// swagger:model resolver
type Resolver struct {

	// accepted payload size
	// Maximum: 8192
	// Minimum: 512
	AcceptedPayloadSize int64 `json:"accepted_payload_size,omitempty"`

	// hold nx
	HoldNx *int64 `json:"hold_nx,omitempty"`

	// hold obsolete
	HoldObsolete *int64 `json:"hold_obsolete,omitempty"`

	// hold other
	HoldOther *int64 `json:"hold_other,omitempty"`

	// hold refused
	HoldRefused *int64 `json:"hold_refused,omitempty"`

	// hold timeout
	HoldTimeout *int64 `json:"hold_timeout,omitempty"`

	// hold valid
	HoldValid *int64 `json:"hold_valid,omitempty"`

	// name
	// Required: true
	// Pattern: ^[A-Za-z0-9-_.:]+$
	Name string `json:"name"`

	// parse resolv conf
	ParseResolvConf bool `json:"parse-resolv-conf,omitempty"`

	// resolve retries
	// Minimum: 1
	ResolveRetries int64 `json:"resolve_retries,omitempty"`

	// timeout resolve
	TimeoutResolve int64 `json:"timeout_resolve,omitempty"`

	// timeout retry
	TimeoutRetry int64 `json:"timeout_retry,omitempty"`
}

// Validate validates this resolver
func (m *Resolver) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcceptedPayloadSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResolveRetries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Resolver) validateAcceptedPayloadSize(formats strfmt.Registry) error {
	if swag.IsZero(m.AcceptedPayloadSize) { // not required
		return nil
	}

	if err := validate.MinimumInt("accepted_payload_size", "body", m.AcceptedPayloadSize, 512, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("accepted_payload_size", "body", m.AcceptedPayloadSize, 8192, false); err != nil {
		return err
	}

	return nil
}

func (m *Resolver) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", m.Name, `^[A-Za-z0-9-_.:]+$`); err != nil {
		return err
	}

	return nil
}

func (m *Resolver) validateResolveRetries(formats strfmt.Registry) error {
	if swag.IsZero(m.ResolveRetries) { // not required
		return nil
	}

	if err := validate.MinimumInt("resolve_retries", "body", m.ResolveRetries, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this resolver based on context it is used
func (m *Resolver) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Resolver) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Resolver) UnmarshalBinary(b []byte) error {
	var res Resolver
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
